#+title: Emacs config file
#+author: Rodrigo Dorantes-Gilardi
#+email: rodgdor@gmail.com
#+options: toc:nil num:nil
I recently went for a full migration to an =org= file, and things be said, my config file looks way
more tidy. I recommend to make the change to have a more *literal programming* kind of =init= file.
* Personal info
	#+begin_src emacs-lisp
	(setq user-full-name "Rodrigo Dorantes Gilardi"
      user-mail-address "rodgdor@gmail.com"
      calendar-latitude 19.4326
      calendar-longitude -99.13
      calendar-location-name "Mexico City")
	#+end_src
* =use-package=
This configuration is inspired by Harry Schwartz
[[https://github.com/hrs/dotfiles/blob/master/emacs/.emacs.d/configuration.org][config file]]. So let's first start by setting =use-package=.

=use-package= is already installed in =init.el= file, but we want to make sure that all packages
added for configuration are installed, for this we use =use-package-ensure=.

#+begin_src emacs-lisp
(require 'use-package-ensure)
(setq use-package-always-ensure t)
#+end_src

Always compile packages, and use the newest version available.

#+BEGIN_SRC emacs-lisp
  (use-package auto-compile
    :config (auto-compile-on-load-mode))

  (setq load-prefer-newer t)
#+END_SRC
* Sensible defaults

Some sensible, rational defaults that help when writing/reading code.

#+begin_src emacs-lisp
;;; Set line numbers and relative mode
(display-line-numbers-mode)
(when (version<= "26.0.50" emacs-version)
    (linum-relative-global-mode 0)
    ;; Show actual number instead of 0 an set
    (setq linum-reative-current-symbol "")
    (set-face-attribute 'linum nil :height 120))

;; Ask y/n instead of yes/no
(fset 'yes-or-no-p 'y-or-n-p)
;; When you double-click on a file in the Mac Finder open it as a
;; buffer in the existing Emacs frame, rather than creating a new
;; frame just for that file.
(setq ns-pop-up-frames nil)
#+end_src
More sensible indentation (2 instead of 8 spaces).
#+begin_src emacs-lisp
(setq-default tab-width 2)
#+end_src
Get proper line breaks, 100 for text and 80 for programming.

#+begin_src emacs-lisp
(dolist (hook '(text-mode-hook latex-mode-hook tex-mode-hook))
  (add-hook hook (lambda () (set-fill-column 100))))
(dolist (hook '(python-mode-hook prog-mode-hook list-mode-hook))
  (add-hook hook (lambda () (set-fill-column 80))))
#+end_src
Wrap paragraphs automatically
  #+begin_src emacs-lisp
(add-hook 'text-mode-hook 'auto-fill-mode)
(add-hook 'org-mode-hook 'auto-fill-mode)
  #+end_src
* Evil
Load evil.
#+begin_src emacs-lisp
(use-package evil
  :config
  (evil-mode 1))
#+end_src
Enable vim-surround everywhere.

#+begin_src emacs-lisp
(use-package evil-surround
  :config
  (global-evil-surround-mode 1))
#+end_src
Use up or down-stream search of visually selected object.
#+begin_src emacs-lisp
(use-package evil-visualstar
    :config
    (global-evil-visualstar-mode)
    (setq evil-visualstar/persistent nil))
#+end_src
* UI
Remove the scroll bar and the menu.
#+begin_src emacs-lisp
(tool-bar-mode 0)
(menu-bar-mode 0)
(scroll-bar-mode 0)
(set-window-scroll-bars (minibuffer-window) nil nil)
#+end_src
Use full-path-name of file in window
#+begin_src emacs-lisp
(setq frame-title-format
      '((:eval (if (buffer-file-name)
                   (abbreviate-file-name (buffer-file-name))
                 "%b"))))
#+end_src
Use solarized theme and set font and mode bar.
#+begin_src emacs-lisp
(use-package solarized-theme
  :config
  (load-theme 'solarized-dark t)
  (let ((line (face-attribute 'mode-line :underline)))
    (set-face-attribute 'mode-line          nil :overline   line)
    (set-face-attribute 'mode-line-inactive nil :overline   line)
    (set-face-attribute 'mode-line-inactive nil :underline  line)
    (set-face-attribute 'mode-line          nil :box        nil)
    (set-face-attribute 'mode-line-inactive nil :box        nil)
    (set-face-attribute 'mode-line-inactive nil :background "#f9f2d9")))
(set-frame-font "IBM Plex Mono-14" nil t)

;; Use moody for the mode bar
(use-package moody
  :config
  (setq x-underline-at-descent-line t)
  (moody-replace-mode-line-buffer-identification)
  (moody-replace-vc-mode))
#+end_src

Hide minor modes from bar.
#+begin_src emacs-lisp
(use-package minions
  :config
  (setq minions-mode-line-lighter ""
        minions-mode-line-delimiters '("" . ""))
  (minions-mode 1))
#+end_src

Highlight the current line.
#+begin_src emacs-lisp
(global-hl-line-mode)
#+end_src

Highlight uncommited changes.
#+begin_src emacs-lisp
(use-package diff-hl
  :config
  (add-hook 'prog-mode-hook 'turn-on-diff-hl-mode))
#+end_src
* Spelling
#+begin_src emacs-lisp
(dolist (hook '(org-mode-hook latex-mode-hook tex-mode-hook git-commit-mode-hook))
  (add-hook hook (lambda () (flyspell-mode 1))))
;;; Setting english to be the spelling language
(setq ispell-program-name "/usr/local/bin/aspell")
(setq ispell-dictionary "english")
#+end_src
* Python
	Let's start with installing =elpy=.
	#+begin_src emacs-lisp
(use-package elpy
  :init
  (elpy-enable)
	:config
  (setq elpy-rpc-backend "jedi")
	;; The path to python3
  (setq elpy-rpc-python-command "/usr/local/Cellar/python/3.6.3/bin/python3"))
	#+end_src
	
Then a little bit of configuration for the interpreter.
#+begin_src emacs-lisp
(use-package python
  :mode ("\\.py\\'" . python-mode) 
  :interpreter ("python" . python-mode)
	:config
	(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt"
      python-shell-prompt-detect-failure-warning nil))
#+end_src

Use =jedi= to autocompletion
#+begin_src emacs-lisp
(use-package jedi
  :config
  (add-hook 'python-mode-hook 'jedi:setup)
  (setq jedi:complete-on-dot t))
#+end_src
Use flycheck for syntax checking.
#+begin_src emacs-lisp
(add-hook 'elpy-mode-hook 'flycheck-mode)
#+end_src
Format according to pep-8 on save.
#+begin_src emacs-lisp
(use-package py-autopep8)
(require 'py-autopep8)
(add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save)
#+end_src
* Org
	First things first
	#+begin_src emacs-lisp
(use-package org)

;; The following is to fix a bug to be able to expand
;; '<s' to code block.
(when (version<= "9.2" (org-version))
    (require 'org-tempo))
	#+end_src
** Display
Use bullets instead of stars.
#+begin_src emacs-lisp
(use-package org-bullets
  :init
  (add-hook 'org-mode-hook 'org-bullets-mode))
#+end_src
Let's add an arrow pointing down if there is some content. Also, let's use syntax highlighting
inside of code blocks.
#+begin_src emacs-lisp
(setq org-ellipsis "⤵")
(setq org-src-tab-acts-natively t)
#+end_src
** Agenda
Add key-binding =\C-ca= to invoke agenda. Also, add a directory for agenda files inside Dropbox.
	 #+begin_src emacs-lisp
(global-set-key "\C-ca" 'org-agenda)
(setq org-agenda-files '("~/Dropbox/org/"))
	 #+end_src
TODO headers can have more states (additionally to =TODO= and =DONE=), also let's add a file to
archive all the TODO trees completed.
#+begin_src emacs-lisp
;; Workflow of TODO keywords
(setq org-todo-keywords
      '((sequence "TODO(t)" "|" "DONE(d!)" "CANCELED(c@/!)")))
;; archive in a datetree
(setq org-archive-location "~/org/archive.org::datetree/")
;; Close TODOs with a timestamp
(setq org-log-done 'time)
#+end_src
** Capture
Emacs allows to capture ideas "on the fly" using a template, that way, you don't need to stop
working on something else when the idea pops-up. We, first are going to create a keybinding for that
function and then we will create the templates.
#+begin_src emacs-lisp
(global-set-key "\C-cc" 'org-capture)
(setq org-capture-templates
  '(("b" "Blog idea"
         entry
         (file "~/Dropbox/notes/blog_ideas.org")
         "* %?\n")))
#+end_src
** Export
*** Classes
		Allow export to different classes, including beamer, markdown, hugo, latex...
		#+begin_src emacs-lisp
(require 'ox-beamer)
(use-package ox-hugo
  :after ox)
;; Pretty html
(use-package ox-twbs)
		#+end_src
*** Code blocks
		Allow to evaluate code in =python=, =C=, =bash=, and =elisp=.

#+begin_src emacs-lisp
(org-babel-do-load-languages
 'org-babel-load-languages '((C . t)
			     (python . t)
			     (emacs-lisp . t)
					 (shell . t)))
#+end_src
*** Latex
		Set the process of compilation of a latex document.
		#+begin_src emacs-lisp
(setq org-latex-pdf-process
      '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
    "bibtex %b"
    "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
    "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
		#+end_src
		
Set sections used in latex section when exported.
#+begin_src emacs-lisp
(add-to-list 'org-latex-classes
             '("article"
               "\\documentclass{article}"
               ("\\section{%s}" . "\\section*{%s}")
               ("\\subsection{%s}" . "\\subsection*{%s}")
               ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
               ("\\paragraph{%s}" . "\\paragraph*{%s}")
               ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
#+end_src
Include minted package in latex exports.
#+begin_src emacs-lisp
;;; Include minted package in all LaTeX reports
(add-to-list 'org-latex-packages-alist '("" "minted"))
(setq org-latex-listing 'minted)
#+end_src
Use the incredible =org-ref= package.
#+begin_src emacs-lisp
(use-package org-ref)
#+end_src
* Magit
Magit is a great package where I prefer its keybinding to =C-x g= rather than =C-x m=.
#+begin_src emacs-lisp
(use-package magit
  :config
  (global-set-key (kbd "C-x g") 'magit-status))
#+end_src
* Helm
Helm is great for file exploration.
#+begin_src emacs-lisp
(use-package helm
  :ensure t
  :config
  (helm-mode 1)
  (global-set-key (kbd "C-x C-f") 'helm-find-files))
#+end_src
